### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by RandomName76** [RuiFilipeCampos/MontyCarlo#65]
Hi,
I'm really interested in using this project for 3D particle interaction.

Unfortunately, I'm having trouble to go through the installation. So I've cloned the repo and started building the docker but an error occurs at step 18/29 "python -c "import MontyCarlo"".

Here is the command prompt result:

[+] Running 1/1
 ! jupyter-notebook Warning manifest unknown                                                                       1.4s
2024/06/21 14:54:23 http2: server: error reading preface from client //./pipe/dockerDesktopLinuxEngine: file has already been closed
[+] Building 63.0s (22/33)                                                                         docker:desktop-linux
 => [jupyter-notebook internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 1.33kB                                                                             0.0s
 => [jupyter-notebook internal] load metadata for docker.io/library/python:3.9.9                                   1.8s
 => [jupyter-notebook internal] load .dockerignore                                                                 0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [jupyter-notebook internal] load build context                                                                 0.1s
 => => transferring context: 124.53kB                                                                              0.1s
 => [jupyter-notebook  1/29] FROM docker.io/library/python:3.9.9@sha256:dd8335df6162579adadd56ff2b9fbd61199da5405  0.0s
 => CACHED [jupyter-notebook  2/29] RUN mkdir app                                                                  0.0s
 => CACHED [jupyter-notebook  3/29] RUN /usr/local/bin/python -m pip install --upgrade pip                         0.0s
 => CACHED [jupyter-notebook  4/29] RUN apt-get update && apt-get install -y python3-opencv                        0.0s
 => CACHED [jupyter-notebook  5/29] RUN pip install opencv-python                                                  0.0s
 => CACHED [jupyter-notebook  6/29] RUN pip install cython                                                         0.0s
 => CACHED [jupyter-notebook  7/29] RUN pip install wheel                                                          0.0s
 => CACHED [jupyter-notebook  8/29] RUN pip install setuptools                                                     0.0s
 => CACHED [jupyter-notebook  9/29] COPY requirements.txt app                                                      0.0s
 => CACHED [jupyter-notebook 10/29] RUN cd app && pip install -r requirements.txt                                  0.0s
 => [jupyter-notebook 11/29] COPY MontyCarlo app/MontyCarlo                                                        0.9s
 => [jupyter-notebook 12/29] COPY setup_linux.py app                                                               0.0s
 => [jupyter-notebook 13/29] COPY setup_version.py app                                                             0.0s
 => [jupyter-notebook 14/29] COPY setup.cfg app/setup.cfg                                                          0.0s
 => [jupyter-notebook 15/29] COPY README.md app                                                                    0.0s
 => [jupyter-notebook 16/29] WORKDIR /app                                                                          0.0s
 => [jupyter-notebook 17/29] RUN python setup_linux.py build_ext -j6 --inplace                                    59.1s
 => ERROR [jupyter-notebook 18/29] RUN python -c "import MontyCarlo"                                               1.0s
------
 > [jupyter-notebook 18/29] RUN python -c "import MontyCarlo":
0.749 seeding with: 0, 0, 0, 123
0.909 Traceback (most recent call last):
0.909   File "<string>", line 1, in <module>
0.909   File "/app/MontyCarlo/__init__.py", line 32, in <module>
0.909     from MontyCarlo.geometry.main import *
0.909   File "MontyCarlo/geometry/main.pyx", line 1, in init MontyCarlo.geometry.main
0.909     # distutils: language = c++
0.909   File "MontyCarlo/materials/electron/GOSfinal.pyx", line 1, in init MontyCarlo.materials.electron.GOSfinal
0.909     #distutils: language = c++
0.909   File "MontyCarlo/materials/electron/main.pyx", line 1, in init MontyCarlo.materials.electron.main
0.909     # distutils: language = c++
0.909   File "MontyCarlo/materials/positron/GOSfinal.pyx", line 1, in init MontyCarlo.materials.positron.GOSfinal
0.910     #distutils: language = c++
0.910   File "MontyCarlo/materials/positron/main.pyx", line 1, in init MontyCarlo.materials.positron.main
0.910     # distutils: language = c++
0.910   File "MontyCarlo/materials/materials.pyx", line 16, in init MontyCarlo.materials.materials
0.910     from .logger import MaterialLogger
0.910   File "/app/MontyCarlo/materials/logger.py", line 8, in <module>
0.910     from ..external.htmlcreator import HTMLDocument
0.911   File "/app/MontyCarlo/external/htmlcreator/__init__.py", line 1, in <module>
0.911     from .document import HTMLDocument
0.911   File "/app/MontyCarlo/external/htmlcreator/document.py", line 8, in <module>
0.911     import pandas as pd
0.911   File "/usr/local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
0.912     from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
0.912   File "/usr/local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 18, in <module>
0.912     from pandas.compat.numpy import (
0.912   File "/usr/local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
0.913     from pandas.util.version import Version
0.913   File "/usr/local/lib/python3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
0.913     from pandas.util._decorators import (  # noqa:F401
0.913   File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
0.913     from pandas._libs.properties import cache_readonly
0.913   File "/usr/local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
0.914     from pandas._libs.interval import Interval
0.914   File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
0.914 ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
0.914 ____INITIALIZING MONTY CARLO_____
0.914 Importing `.settings`
0.914 _________________________________________________________________
0.914 INSTALL PATH:  /app/MontyCarlo
0.914 ----
0.914 DEBUG: False
0.914 ---------------
0.914 PHOTON CUT OFF: 5110.0 MeV
0.914 ----
0.914 ELECTRON CUT OFF: 100000.0 MeV
0.914 ---------------------------------------------
0.914
0.914
0.914 Version: 0.1a0.dev2
0.914
0.914 Importing .tools.interpol1
0.914 Importing .tools.CubicInverseTransform ...
0.914 Importing `.materials.pyRelax`
0.914 Importing `.materials.database`
0.914
0.914   ________________
0.914   > Reading EADL.
0.914 Opening:  /app/MontyCarlo/materials/EADL/1.txt
0.914 Opening:  /app/MontyCarlo/materials/EADL/2.txt
...
0.914 Opening:  /app/MontyCarlo/materials/EADL/99.txt
0.914 Opening:  /app/MontyCarlo/materials/EADL/100.txt
0.914 > Done! EPDL available @ database.EPDL
0.914   ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
0.914
0.914   ________________
0.914   > Reading EPDL.
0.914 > Done! EPDL available @ database.EPDL
0.914   ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
0.914
0.914   ________________
0.914   > Reading EEDL.
0.914 > Done! EPDL available @ database.EEDL
0.914   ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
0.914
0.914 Imported databases
0.914 Saved database.
0.914 Importing .tools.vectors
0.914 Importing `.materials.electron.GOS`
0.914 Importing .tools.RITA
0.914 Importing `.material.photon.CrossSection`
0.914 Importing `.material.photon.pyx`
0.914 Importing `.materials.materials`
0.914 Importing `.materials.logger`
------
failed to solve: process "/bin/sh -c python -c \"import MontyCarlo\"" did not complete successfully: exit code: 1

**Comment by RuiFilipeCampos** [comment]
@RandomName76 Thank you for reporting the issue ! It should be resolved now.

![Screenshot from 2024-06-21 12-39-57](https://github.com/RuiFilipeCampos/MontyCarlo/assets/63464503/fd8ccb44-321c-40f1-b458-4d678710f3c1)

Let me know if you find any other problem.

**Comment by RuiFilipeCampos** [comment]
I'm closing this issue, feel free to reopen if you require any help 

@RandomName76 I've deployed a live demo of the 3d particle interaction here: https://ruicampos.org/interactive.html (may take a bit to load is quite heavy on some computers)

**Comment by RandomName76** [comment]
Thank you for your quick reply. Indeed, I could eventually run the code. The result is cool.

Unfortunately, jupyter notebooks are not great with the security software of my organization (outputs don't show up in general) and I usually go for IDE.
Also, if a user guide could be available for geometry definition, it could be positive as it is a bit confusing at first.

Keep on the good work.
